// Generated by CoffeeScript 1.10.0
(function() {
  console.log("main.js", window.performance.now());

  window.addEventListener("DOMContentLoaded", function(event) {
    return console.log("loaded", performance.now());
  });

}).call(this);
