function template(locals) {
var jade_debug = [ new jade.DebugItem( 1, "jade//index.jade" ) ];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (greeting) {
var jade_indent = [];
jade_debug.unshift(new jade.DebugItem( 0, "jade//index.jade" ));
jade_debug.unshift(new jade.DebugItem( 1, "jade//index.jade" ));
buf.push("<!DOCTYPE html>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 2, "jade//index.jade" ));
buf.push("\n<html lang=\"ja\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 3, "jade//index.jade" ));
buf.push("\n  <head>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 4, "jade//index.jade" ));
buf.push("\n    <meta charset=\"UTF-8\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 5, "jade//index.jade" ));
buf.push("\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 6, "jade//index.jade" ));
buf.push("\n    <title>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</title>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 8, "jade//index.jade" ));
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 9, "jade//index.jade" ));
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 9, "jade//index.jade" ));
buf.push("\n    <script src=\"//code.jquery.com/jquery-2.2.0.min.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 10, "jade//index.jade" ));
buf.push("\n    <script src=\"//cdnjs.cloudflare.com/ajax/libs/lodash.js/4.3.0/lodash.min.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 11, "jade//index.jade" ));
buf.push("\n    <script src=\"//coffeescript.org/extras/coffee-script.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 12, "jade//index.jade" ));
buf.push("\n    <script type=\"text/coffeescript\">");
jade_debug.unshift(new jade.DebugItem( 13, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 13, jade_debug[0].filename ));
buf.push("window.addEventListener \"load\", (event) -> console.log event");
jade_debug.shift();
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 14, "jade//index.jade" ));
buf.push("\n    <script src=\"./js/main.js\">");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n  </head>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 15, "jade//index.jade" ));
buf.push("\n  <body>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 16, "jade//index.jade" ));
buf.push("\n    <div id=\"wrapper\">" + (jade.escape(null == (jade_interp = greeting) ? "" : jade_interp)));
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.shift();
buf.push("</div>");
jade_debug.shift();
jade_debug.unshift(new jade.DebugItem( 17, "jade//index.jade" ));
buf.push("\n    <h2>");
jade_debug.unshift(new jade.DebugItem( undefined, jade_debug[0].filename ));
jade_debug.unshift(new jade.DebugItem( 17, jade_debug[0].filename ));
buf.push("abcdef");
jade_debug.shift();
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n  </body>");
jade_debug.shift();
jade_debug.shift();
buf.push("\n</html>");
jade_debug.shift();
jade_debug.shift();}.call(this,"greeting" in locals_for_with?locals_for_with.greeting:typeof greeting!=="undefined"?greeting:undefined));;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "doctype\nhtml(lang=\"ja\")\n  head\n    meta(charset=\"UTF-8\")\n    meta(http-equiv=\"X-UA-Compatible\", content=\"IE=edge\")\n    title\n    //- link(rel=\"stylesheet\", href=\"css/reset.css\")\n    //- link(rel=\"stylesheet\", href=\"css/main.css\")\n    script(src=\"//code.jquery.com/jquery-2.2.0.min.js\")\n    script(src=\"//cdnjs.cloudflare.com/ajax/libs/lodash.js/4.3.0/lodash.min.js\")\n    script(src=\"//coffeescript.org/extras/coffee-script.js\")\n    script(type=\"text/coffeescript\").\n      window.addEventListener \"load\", (event) -> console.log event\n    script(src=\"./js/main.js\")\n  body\n    #wrapper= greeting\n    h2 abcdef\n");
}
}